### ISSUE TITLE
./bootstrap.pl silently exits without installing anything

### ISSUE THREAD

**Issue by gnull** [tadzik/panda#324]
I've installed the latest rakudo using `rakudobrew`. Now, I'm trying to install `panda` like it was described in `README.md`:

```
$ git clone https://github.com/tadzik/panda.git
Cloning into 'panda'...
^C
$ git clone --recursive https://github.com/tadzik/panda.git
Cloning into 'panda'...
remote: Counting objects: 4909, done.
remote: Total 4909 (delta 0), reused 0 (delta 0), pack-reused 4908
Receiving objects: 100% (4909/4909), 860.12 KiB | 184.00 KiB/s, done.
Resolving deltas: 100% (2227/2227), done.
Checking connectivity... done.
$ cd panda/
$ perl6 ./bootstrap.pl 
==> Bootstrapping Panda
==> Installing panda from a local directory '/home/io/trash/panda'
==> panda depends on File::Find, Shell::Command, JSON::Fast
==> Shell::Command depends on File::Find
==> Fetching File::Find
==> Building File::Find
==> Testing File::Find
t/01-file-find.t .. ok
All tests successful.
Files=1, Tests=11,  1 wallclock secs ( 0.01 usr  0.00 sys +  1.12 cusr  0.11 csys =  1.24 CPU)
Result: PASS
==> Installing File::Find
==> Please make sure that /home/io/.rakudobrew/moar-nom/install/share/perl6/site/bin is in your PATH
$ ls /home/io/.rakudobrew/moar-nom/install/share/perl6/site/bin
$
```

`./bootstrap.pl` exited without installing anything.

I meet the same issue when trying to install `panda` with `rakudobrew`, or when installing it together with rakudo from archive http://rakudo.org/downloads/star/rakudo-star-2016.07.tar.gz

I did the same on another PC and it worked fine.

**Comment by niner** [comment]
Do you actually need to have multiple separate installations of rakudo on 
youre machine? That's the use case rakudobrew is for. It's _not_ meant as a 
means to have one rakudo installation. In other words: it's not meant for 
normal Perl 6 users. It adds a layer of complexity that causes all sorts of 
strange issues.

Please try to remove all traces of rakudobrew and the installed rakudo files 
and install rakudo from source or via a distribution package. Your experience 
should be smoother.

Stefan

**Comment by gnull** [comment]
> Please try to remove all traces of rakudobrew and the installed rakudo files and install rakudo from source or via a distribution package. Your experience should be smoother. 

I've removed `rakudobrew` and tried to install 2016.07 release. Namely:

``` shell
wget http://rakudo.org/downloads/star/rakudo-star-2016.07.tar.gz
tar xvf rakudo-star-2016.07.tar.gz
cd rakudo-star-2016.07
perl ./Configure.pl --gen-moar
make
make install
```

Once `make install` starts to bootstrap panda it prints the same lines as in my first message and exits. After that `./install/bin/perl6` works fine, but there is no `./install/share/perl6/site/bin/panda`.

The interesting detail is that two machines this issue was reproduced on are virtual. I've tested it on two physical (i.e non-virtual) machines and everything worked fine.

**Comment by stmuk** [comment]
What platform are you seeing this issue on?

Sounds similar to #322

**Comment by spebern** [comment]
I have the same issue on arch linux

**Comment by stmuk** [comment]
@spebern Are you able to get a core dump with debugging symbols? You probably need to pass --debug flag to moar config and check ulimit -c at least? 

Also is there any special about your arch system? Is it virtualised?

**Comment by stmuk** [comment]
@spebern also does zef work or not?

**Comment by stmuk** [comment]
Dup of https://github.com/MoarVM/MoarVM/issues/410 ?

**Comment by spebern** [comment]
building zef fails as well with the following output:
`
➜  ~ rakudobrew build zef
Your branch is up-to-date with 'origin/master'.
Failed running /home/ben/.rakudobrew/bin/../moar-nom/install/bin/perl6 -Ilib bin/zef -v install . at /home/ben/.rakudobrew/bin/rakudobrew line 58.
	main::run("/home/ben/.rakudobrew/bin/../moar-nom/install/bin/perl6 -Ilib"...) called at /home/ben/.rakudobrew/bin/rakudobrew line 548
	main::build_zef() called at /home/ben/.rakudobrew/bin/rakudobrew line 355
	main::build_impl("zef", undef, "") called at /home/ben/.rakudobrew/bin/rakudobrew line 116
`

**Comment by stmuk** [comment]
@spebern Are you using a recent zsh (5.2+) as your login shell?

**Comment by spebern** [comment]
Yes

**Comment by spebern** [comment]
@stmuk could you tell me the shell commands to get the output that you need?

**Comment by msellers** [comment]
I have the same issue. In my case it is somehow related to Hardware Lock Elision (HLE/RTM) extensions on Intel Broadwell-E processors (i7 6800K in my case)

I'm on Ubuntu 16.04

@spebern 
```
    cd 
    tar xvf rakudo-star-2016.07.tar.gz 
    cd rakudo-star-2016.07
    perl Configure.pl --backend=moar --gen-moar
    make
    make intall
    export PATH=$HOME/rakudo-star-2016.07/install/bin:$PATH
    export PATH=$HOME/rakudo-star-2016.07/install/share/perl6/site/bin:$PATH
    cd modules/panda/
    ulimit -c unlimited #enable core dump
    perl6 bootstrap.pl 
    cd ../..
    gdb install/bin/moar modules/panda/core 
```

```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from install/bin/moar...(no debugging symbols found)...done.
[New LWP 11263]
[New LWP 12434]
[New LWP 12435]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/matthew/rakudo-star-2016.07/install/bin/moar --execname=/home/matthew/rak'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f66a9f5b960 in _xend () at ../sysdeps/unix/sysv/linux/x86/elision-unlock.c:33
33	../sysdeps/unix/sysv/linux/x86/elision-unlock.c: No such file or directory.
[Current thread is 1 (Thread 0x7f66ab09d700 (LWP 11263))]
(gdb) bt
#0  0x00007f66a9f5b960 in _xend () at ../sysdeps/unix/sysv/linux/x86/elision-unlock.c:33
#1  __lll_unlock_elision (lock=0xccb310, private=0) at ../sysdeps/unix/sysv/linux/x86/elision-unlock.c:29
#2  0x00007f66aaa76199 in uv_mutex_unlock () from //home/matthew/rakudo-star-2016.07/install/lib/libmoar.so
#3  0x00007f66aa9f1a66 in MVM_multi_cache_add () from //home/matthew/rakudo-star-2016.07/install/lib/libmoar.so
#4  0x00007f66a82e3168 in ?? ()
#5  0x00007f66aaa7cfd0 in ?? () from //home/matthew/rakudo-star-2016.07/install/lib/libmoar.so
#6  0x00007f66aa9a4f92 in MVM_frame_invoke () from //home/matthew/rakudo-star-2016.07/install/lib/libmoar.so
#7  0x0000000000ccb7c0 in ?? ()
#8  0x00007f66aa99d075 in MVM_interp_run () from //home/matthew/rakudo-star-2016.07/install/lib/libmoar.so
#9  0x0000000000601dc0 in __JCR_LIST__ ()
#10 0x0000000000000004 in ?? ()
#11 0x0000000000000004 in ?? ()
#12 0x00007f66aaa56b41 in MVM_vm_run_file () from //home/matthew/rakudo-star-2016.07/install/lib/libmoar.so
#13 0x00000000004010ab in main ()
```

I'm not sure how to get better backtrace.

Panda builds fine for me if I use a glibc compiled without lock elision support

I'm still trying to figure out if my chipset is broken or if it is the lock code in MoarVM

**Comment by spebern** [comment]
@msellers I don't get the core file in the panda dir:
`
➜  rakudo-star-2016.07 ls modules/panda 
bin           CONTRIBUTING.md  lib      META.info                README.md       t            update-subtree.pl
bootstrap.pl  ext              LICENSE  projects.json.bootstrap  rebootstrap.pl  testmodules
`

btw. my cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by msellers** [comment]
try running

unlimit coredumpsize

before perl6 bootstrap.pl

**Comment by spebern** [comment]
@msellers no still not there, I hope I'm not just making a dumb mistake

**Comment by spebern** [comment]
I'm not sure if that helps:
I tried the same on a Ubuntu 16.04 VM as guest and got the following output for the core dump after 
bootstrapping panda

```

ben@ubuntu:~/rakudo-star-2016.07$ gdb install/bin/moar modules/panda/core 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from install/bin/moar...(no debugging symbols found)...done.
[New LWP 8611]
[New LWP 8628]
[New LWP 8627]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/ben/rakudo-star-2016.07/install/bin/moar --execname=/home/ben/rakudo-star'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f0100639960 in _xend ()
    at ../sysdeps/unix/sysv/linux/x86/elision-unlock.c:33
33	../sysdeps/unix/sysv/linux/x86/elision-unlock.c: No such file or directory.
[Current thread is 1 (Thread 0x7f010178c700 (LWP 8611))]
(gdb) 
```

**Comment by stmuk** [comment]
This should be fixed by f2369b4

**Comment by spebern** [comment]
yes that works for me! thanks alot!

**Comment by msellers** [comment]
Same. It works now.
